# Generated by Django 4.1 on 2023-02-17 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('carg_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('Carg_descrip', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripcion')),
                ('Carg_salario', models.FloatField(max_length=10, verbose_name='Salario')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='categoria_pro',
            fields=[
                ('Cate_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('Cate_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Cate_descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Categoria productos',
                'verbose_name_plural': 'Categorias productos',
            },
        ),
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('Cli_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('Cli_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Cli_apellido', models.CharField(max_length=10, verbose_name='Apellido')),
                ('Cli_cedula', models.CharField(max_length=10, unique=True, verbose_name='Cedula')),
                ('Cli_ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('Cli_direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('Cli_telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('Emp_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('Emp_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Emp_apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('Emp_direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('Emp_cedula', models.CharField(max_length=10, unique=True, verbose_name='Cedula')),
                ('Emp_telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono')),
                ('Emp_cargo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tendero01.cargo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Cobrador',
            },
        ),
        migrations.CreateModel(
            name='proveedores',
            fields=[
                ('Prov_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('Prov_nit', models.CharField(max_length=16, unique=True, verbose_name='Nit')),
                ('Prov_nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('Prov_replegal', models.CharField(max_length=200, verbose_name='Representante legal')),
                ('Prov_ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('Prov_direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('Prov_telefono', models.CharField(max_length=10, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('Usu_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('Usu_nombre', models.CharField(max_length=10, unique=True, verbose_name='Nombre')),
                ('Usu_password', models.CharField(max_length=10, verbose_name='Contraseña')),
                ('Usu_cargo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tendero01.cargo')),
                ('Usu_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tendero01.empleados')),
            ],
            options={
                'verbose_name': 'Usuarios',
                'verbose_name_plural': 'Ususario',
            },
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('Prod_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('Prod_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Prod_embalaje', models.CharField(max_length=50, verbose_name='Embalaje')),
                ('Prod_cantidad', models.IntegerField(max_length=4, verbose_name='Cantidad')),
                ('Prod_precioin', models.FloatField(max_length=6, verbose_name='Precio inicial')),
                ('Prod_preciomayor', models.FloatField(max_length=6, verbose_name='Precio al por mayor')),
                ('Prod_preciopublico', models.FloatField(max_length=6, verbose_name='Precio a el publico')),
                ('Prod_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tendero01.categoria_pro')),
                ('Prod_provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tendero01.proveedores')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Pago_empleado',
            fields=[
                ('Pagemple_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('Pagemple_sueldo', models.FloatField(max_length=50, verbose_name='Sueldo')),
                ('Pagempl_h_extras', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Horas extras')),
                ('Pagempl_credito', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Credito')),
                ('Pagemple_bono', models.FloatField(blank=True, max_length=10, null=True, verbose_name='Bono')),
                ('Pagemple_carg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tendero01.cargo')),
                ('Pagemple_empl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tendero01.empleados')),
            ],
            options={
                'verbose_name': 'Pago empleado',
                'verbose_name_plural': 'Pagos empleados',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('Fac_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('Fac_codigo', models.CharField(max_length=45, verbose_name='Codigo')),
                ('Fac_fecha', models.DateField(verbose_name='Fecha')),
                ('Fac_cantpro', models.IntegerField(max_length=3, verbose_name='Cantidad de productos')),
                ('Fac_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tendero01.productos')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Detalle_fac',
            fields=[
                ('Det_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('Det_impuesto', models.CharField(max_length=45, verbose_name='Impuesto')),
                ('Det_fac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tendero01.factura')),
                ('Det_id_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tendero01.clientes')),
            ],
            options={
                'verbose_name': 'Detalle factura',
                'verbose_name_plural': 'Detalles Facturas',
            },
        ),
    ]
